name: Build and deploy Streamlit app to Azure Web App

on:
  push:
    branches:
      - main  # Deploy whenever changes are pushed to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust the Python version if needed

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip the application for deployment
        run: zip -r streamlit_app.zip ./* -x '*.git*' '*venv/*'  # Exclude .git and virtual environment folders

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-app-package
          path: streamlit_app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: streamlit-app-package

      - name: Unzip the package
        run: unzip streamlit_app.zip

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'medical-record-analyzer'  # Your Azure Web App name
          package: streamlit_app.zip  # Path to the zipped application
